### ISSUE TITLE
Internet Explorer compatibility

### ISSUE THREAD

**Issue by innerjoin** [jazz-community/rtc-git-connector#2] opened 2018-02-04 11:12 UTC
According to the `README`, the git connector does not yet work with Internet Explorer. As IE is still widely used, we should overcome this limitation.

**Comment by innerjoin** [comment] 2018-07-24 14:54
@MartinBenninger Unfortunately, I still see many people in our company that use IE for their Jazz work.
What are the limitations today in IE and how easily could they be addressed? Is the user properly informed that IE is not supported?

**Comment by MartinBenninger** [comment] 2018-08-02 11:33
@innerjoin Yes, that is unfortunate :smile:
The issue is that the plugin has quite a few dependencies that use newer JavaScript features that are not supported yet in IE. I've tried to get this working using various methods (webpack plugins, babel polyfills, and babel compiler) but without total success.

Currently the plugin opens a popup with a message stating that Internet Explorer is not supported and that the user should use Chrome or Firefox instead.

This definitely should be possible but might take some time to make sure that all features are working correctly. Let me know if you have any further ideas or input on this (am I missing something obvious?).

PS: I haven't considered this to be very high priority because no users have mentioned it being a problem yet.

**Comment by innerjoin** [comment] 2018-08-02 12:39
Ok, so I assume that most Git* users in our company are modern and smart people that use a proper browser, not IE :-)

You could slightly modify the README and state that we are looking for someone who implements IE compatibility and reference this issue.

**Comment by rolfnelson** [comment] 2019-06-25 18:31
With Microsoft switching to Chromium I think this will come now in time.

**Comment by MartinBenninger** [comment] 2019-12-03 15:09
I'm closing this as "Won't fix" because people shouldn't be using IE anymore. There are plenty of good alternatives like Chrome, Firefox, or Edge.

If someone else needs IE support they are free to implement it.

**Closed by MartinBenninger** 2019-12-03 15:09 UTC
Labels: bug, good first issue, help wanted
